# Generated by Django 5.2.11 on 2026-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheltuieli', '0002_alter_cheltuialamodel_deductibila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheltuialamodel',
            name='deductibila',
            field=models.CharField(choices=[('Deductibila integral', 'Deductibila integral'), ('Obiect de inventar (deductibil integral)', 'Obiect de inventar (deductibil integral)'), ('Mijloc fix peste 2500 RON (ded. integral cu amortizare)', 'Mijloc fix peste 5000 RON (ded. integral cu amortizare)'), ('Auto, chirii, utilitati 50% din valoarea lor', 'Vehicule nefolosite exclusiv in activitate, 50% (art. 68 alin. 7 lit. k)'), ('Sport, sali de fitness etc. max. 100 EUR pe an', 'Sport, sali de fitness etc. max. 100 EUR pe an'), ('Pensie pilon III max. 400 EUR pe an', 'Pensie pilon III max. 400 EUR pe an'), ('Asigurari medicale private max. 400 EUR pe an', 'Asigurari medicale private max. 400 EUR pe an'), ('Mese protocol max. 2% baza de calcul', 'Mese protocol max. 2% baza de calcul'), ('Deductibila integral salarii', 'Deductibila integral salarii'), ('Ajutoare diverse pt. angajati max. 5% din total salarii pe an', 'Ajutoare diverse pt. angajati max. 5% din total salarii pe an'), ('Contributii obligatorii asociatii, organizatii max. 5% din brut', 'Contributii obligatorii asociatii, organizatii max. 5% din brut'), ('Cotizatii voluntare asociatii, organizatii max. 4000 EUR pe an', 'Cotizatii voluntare asociatii, organizatii max. 4000 EUR pe an')], default='Deductibila integral', max_length=300),
        ),
    ]
