# Generated by Django 5.2.11 on 2026-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setarimodel',
            name='nume',
            field=models.CharField(max_length=250),
        ),
    ]
